backend:
    name: github
    repo: awesome1888/grayscale-promo-gatsbyjs-starter
media_folder: static/assets
public_folder: assets
media_folder_relative: true
collections:
    - name: block
      label: Block
      folder: content/blocks
      create: true
      identifier_field: id
      fields:
          # https://www.netlifycms.org/docs/widgets/
          - name: id
            label: ID
          - name: sort
            label: Sort
            widget: number
            valueType: int
          - name: body
            label: Body
            widget: markdown
          - label: 'Graphics'
            name: 'graphics'
            widget: 'list'
            fields:
                - name: image
                  label: 'Image'
                  widget: 'image'
                  media_library:
                      config:
                      multiple: true
                - name: author
                  label: 'Author'
                  widget: string
                  required: false
                - name: source
                  label: 'Source'
                  widget: string
                  required: false
          - label: Widget
            name: widget
            widget: select
            options:
                - { label: 'Standard', value: 'StandardBlock' }
                - { label: 'Accent', value: 'AccentBlock' }
                - { label: 'Quote', value: 'QuoteBlock' }
            required: false
          - name: effect
            label: Effect
            widget: select
            options:
                - { label: 'Fade+Slide-in to left', value: 'fade-slide-left' }
                - { label: 'Fade+Slide-in to right', value: 'fade-slide-right' }
                - { label: 'Fade+Slide-in to top', value: 'fade-slide-top' }
                - {
                      label: 'Fade+Slide-in to bottom',
                      value: 'fade-slide-bottom',
                  }
            required: false
          - name: effectTimeout
            label: Effect timeout
            widget: number
            valueType: int
            default: 0
          - label: Font size
            name: fontSize
            widget: select
            options:
                - { label: 'Small', value: 'small' }
                - { label: 'Standard', value: 'standard' }
                - { label: 'Medium', value: 'medium' }
                - { label: 'Large', value: 'large' }
            default: standard
            required: false
